load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "command",
    srcs = ["command.go"],
    importpath = "ok.build/cli/command",
)

package(default_visibility = ["//cli:__subpackages__"])
